---
apiVersion: v1
kind: Pod
metadata:
  name: v1
spec:
  containers:
  - name: app
    image: appv1:latest
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 3000
  - name: db
    image: dbv1:latest
    imagePullPolicy: IfNotPresent
---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: v2
#   labels:
#     app: web
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: web
#   template:
#     metadata:
#       labels:
#         app: web
#     spec:
#       containers:
#         - name: front-end
#           image: nginx
#           ports:
#             - containerPort: 80
#         - name: rss-reader
#           image: nickchase/rss-php-nginx:v1
#           ports:
#             - containerPort: 88
